"""Allow role = 'principal' on users

The principal is this school's admin. `ck_users_role` pinned `role` to
'teacher' or 'student', so until this runs the database itself rejects the new
role — a principal sign-up fails on the INSERT with a constraint violation, not
in the API layer.

Hand-written rather than autogenerated: Alembic does not compare CHECK
constraints, so `--autogenerate` produces an empty migration for this and the
drift would go unnoticed until the first principal signed up.

Nothing is backfilled. No existing row changes role, and no account is promoted
— the two accounts already in the database keep exactly the roles they have.
Creating the first principal is a deliberate sign-up.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-17
"""

from typing import Sequence, Union

from alembic import op

revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

CONSTRAINT = "ck_users_role"

OLD_ROLES = "role IN ('teacher', 'student')"
NEW_ROLES = "role IN ('teacher', 'student', 'principal')"


def upgrade() -> None:
    # Dropped and recreated rather than altered: SQL has no "widen a CHECK"
    # statement, and on PostgreSQL an ADD CONSTRAINT validates every existing
    # row, which is what we want — it would fail loudly if a row somehow held a
    # role the new list still does not allow.
    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_constraint(CONSTRAINT, type_="check")
        batch_op.create_check_constraint(CONSTRAINT, NEW_ROLES)


def downgrade() -> None:
    # Any principal has to go first, or recreating the narrower constraint
    # fails on their row. Deleting accounts in a downgrade would be worse than
    # refusing, so this stops and says what to do.
    principals = op.get_bind().exec_driver_sql(
        "SELECT count(*) FROM users WHERE role = 'principal'"
    ).scalar()

    if principals:
        raise RuntimeError(
            f"{principals} user(s) have role='principal'. Reassign or remove "
            "them before downgrading past 0002, or the narrower CHECK "
            "constraint cannot be recreated."
        )

    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_constraint(CONSTRAINT, type_="check")
        batch_op.create_check_constraint(CONSTRAINT, OLD_ROLES)
