"""Co-teachers, unassigned classes, and the approval queue

Phase 5 of the role rebuild, and the phase that was blocked on the
notifications design. Four changes, one migration, because they only make
sense together:

1. **`classes.teacher_id` becomes nullable.** The principal creates classes
   now, and a class made in August before anyone has been given it is a real
   thing with nobody teaching it. Null means unassigned.

2. **`class_teachers`** — a class may be taught by several teachers. One owner
   (`classes.teacher_id`) plus a set, rather than the set alone, so
   `uq_classes_teacher_name` keeps meaning what it always did: two teachers
   may each have a "Nursery" and neither sees the other's.

3. **`change_requests`** — a teacher creating a class, deleting one, adding a
   pupil or removing one now asks instead of doing. The row is the asking.

4. **`notifications`** — where that asking turns up, and how the answer gets
   back. Date, time, source, audience (one account or a broadcast), and the
   message as stored text.

Nothing is backfilled. Existing classes keep the teacher they have, and
`class_teachers` starts empty because the owner is deliberately **not**
repeated in it — one fact, one place.

> **Written by hand, not autogenerated, and here is why that mattered.**
> `classes` carries two things `--autogenerate` cannot see: the expression
> index `uq_classes_teacher_name` on `lower(name)`, which Alembic cannot
> reflect on SQLite at all, and the `class_roster` view, which `env.py`
> excludes by name. A generated batch operation would have tried to reflect
> the table to rebuild it, lost the index, and left the view pointing at a
> table that had been dropped and remade underneath it. So the order below is
> explicit: drop the view, drop the index, change the column, put both back.
> The view's SQL is a **copy** of the one in 0001, not an import — a migration
> has to keep doing what it did the day it was written.

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-20
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "0006"
down_revision: Union[str, None] = "0005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# A copy of the view as 0001 created it, so dropping and recreating it here
# restores exactly what was there. Do not import the live constant.
CLASS_ROSTER_VIEW = """
CREATE VIEW class_roster AS
SELECT
    c.class_id AS class_id,
    c.name AS class_name,
    ROW_NUMBER() OVER (
        PARTITION BY s.class_id
        ORDER BY lower(s.name), s.student_id
    ) AS roll_number,
    s.name AS student_name,
    c.teacher_id AS teacher_id,
    s.student_id AS student_id
FROM students AS s
JOIN classes AS c ON c.class_id = s.class_id
"""

CLASS_NAME_INDEX = "uq_classes_teacher_name"

# Written out rather than imported from app.models for the same reason as the
# view: the CHECK a migration writes is the one that ran.
REQUEST_KINDS = ("class_create", "class_delete", "student_add", "student_remove")
REQUEST_STATUSES = ("pending", "approved", "rejected")
NOTIFY_AUDIENCES = ("user", "broadcast")


def _in_list(values: tuple[str, ...]) -> str:
    joined = "', '".join(values)
    return f"('{joined}')"


def upgrade() -> None:
    # --- 1. classes.teacher_id becomes nullable ------------------------------
    #
    # The view goes first: on SQLite the column change rebuilds the whole
    # table, and a view left pointing at a table that is dropped and remade
    # underneath it is the kind of breakage that only shows up on the next
    # roster read. The index goes second because Alembic cannot reflect an
    # expression index on SQLite, so a rebuild would silently lose it.
    op.execute("DROP VIEW IF EXISTS class_roster")
    op.drop_index(CLASS_NAME_INDEX, table_name="classes")

    with op.batch_alter_table("classes") as batch:
        batch.alter_column(
            "teacher_id", existing_type=sa.String(length=16), nullable=True
        )

    # Raw SQL, not create_index: the expression half — lower(name) — is not
    # something op.create_index can express portably.
    op.execute(
        f"CREATE UNIQUE INDEX {CLASS_NAME_INDEX} "
        "ON classes (teacher_id, lower(name))"
    )
    op.execute(CLASS_ROSTER_VIEW)

    # --- 2. class_teachers ---------------------------------------------------
    op.create_table(
        "class_teachers",
        sa.Column("class_id", sa.String(length=16), nullable=False),
        sa.Column("teacher_id", sa.String(length=16), nullable=False),
        sa.Column("assigned_by_user_id", sa.String(length=16), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"], ["classes.class_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"], ["teachers.teacher_id"], ondelete="CASCADE"
        ),
        # The assignment outlives the principal who made it.
        sa.ForeignKeyConstraint(
            ["assigned_by_user_id"], ["users.user_id"], ondelete="SET NULL"
        ),
        # The pair is the key, so the same teacher cannot be added twice —
        # which is what lets the picker send the whole set rather than a diff.
        sa.PrimaryKeyConstraint("class_id", "teacher_id"),
    )
    # The key leads on class_id, so it answers "who teaches this class" but
    # not "which classes does this teacher take" — the question every
    # dashboard load asks.
    op.create_index(
        "ix_class_teachers_teacher_id", "class_teachers", ["teacher_id"]
    )

    # --- 3. change_requests --------------------------------------------------
    op.create_table(
        "change_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "requested_by_teacher_id", sa.String(length=16), nullable=True
        ),
        sa.Column("requested_by_name", sa.String(length=120), nullable=False),
        sa.Column("class_id", sa.String(length=16), nullable=True),
        sa.Column("student_id", sa.String(length=16), nullable=True),
        sa.Column("summary", sa.String(length=300), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("decided_by_user_id", sa.String(length=16), nullable=True),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.Column("decision_note", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        # SET NULL on all four links: a teacher leaving, or the very class
        # they asked about being deleted, must not erase the school's record
        # of what was asked and who decided it. requested_by_name is the
        # denormalised copy that keeps the queue readable afterwards.
        sa.ForeignKeyConstraint(
            ["requested_by_teacher_id"],
            ["teachers.teacher_id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["class_id"], ["classes.class_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["students.student_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"], ["users.user_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid", name="uq_change_requests_uuid"),
        # Named, both of them. An unnamed CHECK is named by the database and
        # the downgrade then has nothing to look up — the mistake 0004
        # recorded.
        sa.CheckConstraint(
            f"kind IN {_in_list(REQUEST_KINDS)}", name="ck_change_requests_kind"
        ),
        sa.CheckConstraint(
            f"status IN {_in_list(REQUEST_STATUSES)}",
            name="ck_change_requests_status",
        ),
    )
    op.create_index(
        "ix_change_requests_status", "change_requests", ["status"]
    )
    op.create_index(
        "ix_change_requests_requested_by_teacher_id",
        "change_requests",
        ["requested_by_teacher_id"],
    )

    # --- 4. notifications ----------------------------------------------------
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        # Date and time apart, as the tab reads them: grouped under a day,
        # each line stamped with a clock time. created_at is kept for
        # ordering, which is the one job a split date and time do badly.
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("time", sa.Time(), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("audience", sa.String(length=16), nullable=False),
        sa.Column("user_id", sa.String(length=16), nullable=True),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=True),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        # CASCADE: a deleted account's notices go with it.
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], ondelete="CASCADE"
        ),
        # SET NULL: the notice that something was asked for is still true
        # after the request itself has been cleared away.
        sa.ForeignKeyConstraint(
            ["request_id"], ["change_requests.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid", name="uq_notifications_uuid"),
        sa.CheckConstraint(
            f"audience IN {_in_list(NOTIFY_AUDIENCES)}",
            name="ck_notifications_audience",
        ),
        # A 'user' notice with nobody to deliver it to, and a broadcast
        # addressed to one person, are both nonsense the table should not be
        # able to hold.
        sa.CheckConstraint(
            "(audience = 'user' AND user_id IS NOT NULL) "
            "OR (audience = 'broadcast' AND user_id IS NULL)",
            name="ck_notifications_addressed",
        ),
    )
    op.create_index("ix_notifications_user_id", "notifications", ["user_id"])


def downgrade() -> None:
    op.drop_index("ix_notifications_user_id", table_name="notifications")
    op.drop_table("notifications")

    op.drop_index(
        "ix_change_requests_requested_by_teacher_id",
        table_name="change_requests",
    )
    op.drop_index("ix_change_requests_status", table_name="change_requests")
    op.drop_table("change_requests")

    op.drop_index("ix_class_teachers_teacher_id", table_name="class_teachers")
    op.drop_table("class_teachers")

    # Going back to NOT NULL cannot work while an unassigned class exists, and
    # there is no honest value to invent for one — a class nobody teaches
    # cannot be given a teacher by a migration. Deleted rather than guessed:
    # an unassigned class has no students either way, because registering into
    # one is the principal's act and they would have assigned it first.
    op.execute("DELETE FROM classes WHERE teacher_id IS NULL")

    op.execute("DROP VIEW IF EXISTS class_roster")
    op.drop_index(CLASS_NAME_INDEX, table_name="classes")

    with op.batch_alter_table("classes") as batch:
        batch.alter_column(
            "teacher_id", existing_type=sa.String(length=16), nullable=False
        )

    op.execute(
        f"CREATE UNIQUE INDEX {CLASS_NAME_INDEX} "
        "ON classes (teacher_id, lower(name))"
    )
    op.execute(CLASS_ROSTER_VIEW)
